name: Raise a PR for package update in rudder sources

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  create-upgrade-pr:
    name: bump wht version and create a pull request
    runs-on: ubuntu-latest


    steps:
      - name: Initialise Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Perform package update
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git clone https://${{secrets.PAT}}@github.com/rudderlabs/rudder-sources.git
          cd rudder-sources
          git checkout -b chore/whtupgrade$GITHUB_REF_NAME

          go get github.com/rudderlabs/wht@$GITHUB_REF_NAME

          go mod vendor
          go mod tidy

          git commit -m "chore: wht upgrade to version $GITHUB_REF_NAME"
          git push -u origin chore/whtupgrade$GITHUB_REF_NAME

          gh pr create --fill
