models:
  - name: llm_prompt_response_first_name
    model_type: llm_prompt_response
    model_spec:
      inputs:
        - inputs/rsMainIdStitchedFeatures
      target_field: FIRST_NAME
      output_field: first_name
      prompt: "You are provided with a comma-sepatated list of first name values for a user. Suggest the most likely first name. Return only the first name and no other text"
      endpoint: openai
      model: gpt-4-1106-preview	
